# Generated by Django 2.2 on 2019-04-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20190412_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Parâmetro para definir se o usuário está apto a algo relacionado a NF-e'), ('Permissão Dois', 'A segunda permissão para algo'), ('Permissão Três', 'A terceira permissão para algo'), ('ver_dashboard', 'Acesso para visualizar o dashboard de vendas.'))},
        ),
    ]
