# Generated by Django 2.2 on 2019-05-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0005_auto_20190430_1704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itenspedido',
            unique_together={('venda', 'produto')},
        ),
    ]
