# Generated by Django 2.2 on 2019-04-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20190412_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': (('visualizar_pessoa_detail', 'Permissão para visualizar as informações de uma pessoa específica.'),), 'verbose_name_plural': 'Pessoinhas'},
        ),
        migrations.AlterUniqueTogether(
            name='pessoa',
            unique_together={('first_name', 'age')},
        ),
    ]
