# Generated by Django 2.2 on 2019-05-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190430_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('NDA ', 'Nada')], default='NDA ', max_length=2),
        ),
    ]
