# Generated by Django 2.2 on 2019-05-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_pessoa_tipo_pessoa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pessoa',
            unique_together=set(),
        ),
    ]
